// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwF4-5nsIiqESJaYN9is8RCi4dZ50FnU',
    appId: '1:1031862612764:web:57ab8db508fa2c2c8340d9',
    messagingSenderId: '1031862612764',
    projectId: 'quekerguard-f4d6f',
    authDomain: 'quekerguard-f4d6f.firebaseapp.com',
    storageBucket: 'quekerguard-f4d6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQ-Xf705NdRgIsvE_wp-ZNPq-66nvqaY',
    appId: '1:1031862612764:android:cf6313e451c2ba608340d9',
    messagingSenderId: '1031862612764',
    projectId: 'quekerguard-f4d6f',
    storageBucket: 'quekerguard-f4d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEWnc1S1_bpann4PN0ogyK8eHlFXABBc',
    appId: '1:1031862612764:ios:0f9af75590e740308340d9',
    messagingSenderId: '1031862612764',
    projectId: 'quekerguard-f4d6f',
    storageBucket: 'quekerguard-f4d6f.appspot.com',
    iosBundleId: 'com.example.mobQueker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEWnc1S1_bpann4PN0ogyK8eHlFXABBc',
    appId: '1:1031862612764:ios:a78593d7eb530b218340d9',
    messagingSenderId: '1031862612764',
    projectId: 'quekerguard-f4d6f',
    storageBucket: 'quekerguard-f4d6f.appspot.com',
    iosBundleId: 'com.example.mobQueker.RunnerTests',
  );
}
